### PR TITLE
Include the semantic of arithmetic operation

### LINKED ISSUE #2: Include the semantic of arithmetic operations
I'm converting everything to Kotlin because I was having too many problems with Null Pointer Exception with Java. #1 is the current list of what has to be done for now.
While is everything being refactored, should be good to check the current behaviour of the arithmetic operations in the semantic phase.

Arithmetic Operations:
- Addition
  - Allowed to integer and rational operands
  - The result depends on the operands. If both are integers, the result is an integer. Otherwise, the result is rational.
- Subtraction
  - Allowed to integer and rational operands
  - The result depends on the operands. If both are integers, the result is an integer. Otherwise, the result is rational.
- Multiplication
  - Allowed to integer and rational operands
  - The result depends on the operands. If both are integers, the result is an integer. Otherwise, the result is rational.
- Rational Division
  - Allowed to integer and rational operands
  - The result is always a rational value
- Integer Division
  - Allowed to integer operands
  - The result is always an integer value
- Modulo
  - Allowed to integer operands
  - The result is always an integer value

### PR DESCRIPTION
**Pull request by meevee98**
Start of #2 
While refactoring the semantic of arithmetic operations, I'm also adapting the conversion of the analysis to web assembly text format because this is a feature that the Java version already had.

### CODE REVIEW

**Review by Thacryba — APPROVED** [review]
I've finished the review. Now I'm gonna do some tests...

**Comment by Thacryba** [comment]
Hello! 
I was making some tests and this is what I got:

The division between integers put in a rational variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

The division between integers put in an integer variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The division between integers put in a boolean variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Integer'`

The division between integers put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Integer'`

The division between integers put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

The division between rationals put in an integer variable.
Expected: Mistyping Error.
Result: `line 4:4 Incompatible types between 'Rational' and 'Integer'`

The division between rationals put in a rational variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The division between rationals put in a boolean variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

The division between rationals put in a character variable.
Expected: Mistyping Error.
Result:`line 8:4 Incompatible types between 'Character' and 'Rational'`

The division between rationals put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

The division between rational and integer put in an integer variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

The division between rational and integer put in a rational variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The division between rational and integer put in a boolean variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

The division between rational and integer put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

The division between rational and integer put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

The multiplication between integers put in a rational variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

The multiplication between integers put in an integer variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The multiplication between integers put in a boolean variable.
Expected: Mistyping Error.
Result: `line 7:10 Cannot resolve symbol 'boolean'`

The multiplication between integers put in a character variable.
Expected: Mistyping Error.
Result: `line 7:10 Cannot resolve symbol 'character'`

The multiplication between integers put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

The multiplication between rationals put in an integer variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

The multiplication between rationals put in a rational variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The multiplication between rationals put in a boolean variable.
Expected: Mistyping Error.
Result: `line 7:10 Cannot resolve symbol 'boolean'`

The multiplication between rationals put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

The multiplication between rationals put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

The multiplication between rational and integer put in an integer variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

The multiplication between rational and integer put in a rational variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The multiplication between rational and integer put in a boolean variable.
Expected: Mistyping Error.
Result: `line 7:10 Cannot resolve symbol 'boolean'`

The multiplication between rational and integer put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

The multiplication between rational and integer put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

The sum between rationals put in a rational variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The sum between rationals put in an integer variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

The sum between rationals put in a boolean variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

The sum between rationals put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

The sum between integers put in a rational variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

The sum between integers put in an integer variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The sum between integers put in a boolean variable.
Expected: Mistyping Error.
Result: `line 7:10 Cannot resolve symbol 'boolean'`

The sum between integers put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Integer'`

The sum between integers put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

The sum between rational and integer put in an integer variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

The sum between rational and integer put in a rational variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The sum between rational and integer put in a boolean variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

The sum between rational and integer put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

The sum between rational and integer put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

The subtraction between rationals put in a rational variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The subtraction between rationals put in an integer variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

The subtraction between rationals put in a boolean variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

The subtraction between rationals put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

The subtraction between rationals put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

The subtraction between integers put in a rational variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

The subtraction between integers put in an integer variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The subtraction between integers put in a boolean variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Integer'`

The subtraction between integers put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Integer'`

The subtraction between integers put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

The subtraction between rational and integer put in an integer variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

The subtraction between rational and integer put in a rational variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The subtraction between rational and integer put in a boolean variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

The subtraction between rational and integer put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

The subtraction between rational and integer put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

The modulo between integers put in a rational variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

The modulo between integers put in an integer variable.
Expected: It should be no error.
Result: The code was translated to WAT with no errors.

The modulo between integers put in a boolean variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Integer'`

The modulo between integers put in a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Integer'`

The modulo between integers put in a string variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

The modulo between rationals put in a rational variable.
Expected: Mistyping Error.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

The modulo between rationals put in an integer variable.
Expected: Mistyping Error.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

The modulo between rationals put in a boolean variable.
Expected: Mistyping Error.
Result: `line 7:10 Cannot resolve symbol 'boolean'`

The modulo between rationals put in a character variable.
Expected: Mistyping Error.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

The modulo between rationals put in a string variable.
Expected: Mistyping Error.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

The modulo between rational and integer put in an integer variable.
Expected: Mistyping Error.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

The modulo between rational and integer put in a rational variable.
Expected: Mistyping Error.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

The modulo between rational and integer put in a boolean variable.
Expected: Mistyping Error.
Result: `line 7:10 Cannot resolve symbol 'boolean'`

The modulo between rational and integer put in a character variable.
Expected: Mistyping Error.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

The modulo between rational and integer put in a string variable.
Expected: Mistyping Error.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

There's no validation for the division by zero.

Some variations of this code were used in the test:

```
procedimento principal
inicio
    var1: racional;
    var1 <- 30.5;
    var2: racional;
    var2 <- 2.0;
    var3: racional;
    var3 <- var1 / var2;
fim
```

**Comment by Thacryba** [comment]
Hello!
I was making some tests and this is what I got: 👍 

<details><summary>Tests</summary><br/>
<details><summary>Division</summary>

1. The result of the division between integers, assigned into a rational variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

1. The result of the division between integers, assigned into an integer variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the division between integers, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Integer'`

1. The result of the division between integers, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Integer'`

1. The result of the division between integers, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

1. The result of the division between rationals, assigned into an integer variable.
Expected: Error Type.
Result: `line 4:4 Incompatible types between 'Rational' and 'Integer'`

1. The result of the division between rationals, assigned into a rational variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the division between rationals, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

1. The result of the division between rationals, assigned into a character variable.
Expected: Error Type.
Result:`line 8:4 Incompatible types between 'Character' and 'Rational'`

1. The result of the division between rationals, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

1. The result of the division between rational and integer, assigned into an integer variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

1. The result of the division between rational and integer, assigned into a rational variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the division between rational and integer, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

1. The result of the division between rational and integer, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

1. The result of the division between rational and integer, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`
</details>
<details><summary>Multiplication</summary>

1. The result of the multiplication between integers, assigned into a rational variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

1. The result of the multiplication between integers, assigned into an integer variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the multiplication between integers, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Integer'`

1. The result of the multiplication between integers, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Integer'`

1. The result of the multiplication between integers, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

1. The result of the multiplication between rationals, assigned into an integer variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

1. The result of the multiplication between rationals, assigned into a rational variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the multiplication between rationals, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

1. The result of the multiplication between rationals, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

1. The result of the multiplication between rationals, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

1. The result of the multiplication between rational and integer, assigned into an integer variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

1. The result of the multiplication between rational and integer, assigned into a rational variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the multiplication between rational and integer, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

1. The result of the multiplication between rational and integer, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

1. The result of the multiplication between rational and integer, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`
</details>
<details><summary>Addition</summary>

1. The result of the addition between rationals, assigned into a rational variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the addition between rationals, assigned into an integer variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

1. The result of the addition between rationals, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

1. The result of the addition between rationals, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

1. The result of the addition between rationals, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

1. The result of the addition between integers, assigned into a rational variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

1. The result of the addition between integers, assigned into an integer variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the addition between integers, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Integer'`

1. The result of the addition between integers, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Integer'`

1. The result of the addition between integers, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

1. The result of the addition between rational and integer, assigned into an integer variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

1. The result of the addition between rational and integer, assigned into a rational variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the addition between rational and integer, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

1. The result of the addition between rational and integer, assigned into a character variable.
Expected: Mistyping Error.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

1. The result of the addition between rational and integer, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`
</details>
<details><summary>Subtraction</summary>

1. The result of the subtraction between rationals, assigned into a rational variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the subtraction between rationals, assigned into an integer variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

1. The result of the subtraction between rationals, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

1. The result of the subtraction between rationals, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

1. The result of the subtraction between rationals, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`

1. The result of the subtraction between integers, assigned into a rational variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

1. The result of the subtraction between integers, assigned into an integer variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the subtraction between integers, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Integer'`

1. The result of the subtraction between integers, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Integer'`

1. The result of the subtraction between integers, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

1. The result of the subtraction between rational and integer, assigned into an integer variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Integer' and 'Rational'`

1. The result of the subtraction between rational and integer, assigned into a rational variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the subtraction between rational and integer, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Rational'`

1. The result of the subtraction between rational and integer, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Rational'`

1. The result of the subtraction between rational and integer, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Rational'`
</details>
<details><summary>Modulo</summary>

1. The result of the modulo of the division between integers, assigned into a rational variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Rational' and 'Integer'`

1. The result of the modulo of the division between integers, assigned into an integer variable.
Expected: It should be no semantic error.
Result: The code was translated to WAT with no semantic errors.

1. The result of the modulo of the division between integers, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Boolean' and 'Integer'`

1. The result of the modulo of the division between integers, assigned into a character variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'Character' and 'Integer'`

1. The result of the modulo of the division between integers, assigned into a string variable.
Expected: Error Type.
Result: `line 8:4 Incompatible types between 'String' and 'Integer'`

1. The result of the modulo of the division between rationals, assigned into a rational variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

1. The result of the modulo of the division between rationals, assigned into an integer variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

1. The result of the modulo of the division between rationals, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

1. The result of the modulo of the division between rationals, assigned into a character variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

1. The result of the modulo of the division between rationals, assigned into a string variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

1. The result of the modulo of the division between rational and integer, assigned into an integer variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

1. The result of the modulo of the division between rational and integer, assigned into a rational variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

1. The result of the modulo of the division between rational and integer, assigned into a boolean variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

1. The result of the modulo of the division between rational and integer, assigned into a character variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`

1. The result of the modulo of the division between rational and integer, assigned into a string variable.
Expected: Error Type.
Result: `line 8:17 mismatched input 'mod' expecting {''*'', ''/''}`
</details>

Some variations of this code were used in the test:

```
procedimento principal
inicio
    var1: racional;
    var1 <- 30.5;
    var2: racional;
    var2 <- 2.0;
    var3: racional;
    var3 <- var1 / var2;
fim
```
</details>

In my tests, I've noticed that there's no validation for the division by zero.

**Comment by meevee98** [comment]
Thank you for the tests @Thacryba

> In my tests, I've noticed that there's no validation for the division by zero.

Yes, I noticed that too. I was planning to do the verification of division by zero in another pull request. Do you think that should be in this?

**Comment by Thacryba** [comment]
You're welcome!

> Yes, I noticed that too. I was planning to do the verification of division by zero in another pull request. Do you think that should be in this?

I think it could be in another PR... This is related to arithmetic, but it's a special case and I don't see much priority to this right now.

**Pull request merged**
